{% set name = "colab-convert" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45a1bb36ed3580b7c5f40d70ce104da375be89537925fba2643a9372cc002dc5

build:
  noarch: python
  number: 0
  entry_points:
    - colab-convert = colab_convert.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - colab_convert

about:
  home: https://github.com/MSFTserver/colab-convert
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Convert .py files runnable in VSCode/Python or Atom/Hydrogen to jupyter/colab .ipynb notebooks and vice versa"
  doc_url: https://github.com/MSFTserver/colab-convert
  dev_url: https://github.com/MSFTserver/colab-convert

extra:
  recipe-maintainers:
    - MSFTserver
