{% set name = "colab-convert" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16a30d8b34dc570d1171586f7ae63be8402371cd664f4bcfbbf5066547095d0f

build:
  noarch: python
  number: 0
  entry_points:
    - colab-convert = colab_convert.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - colab_convert

about:
  home: https://github.com/MSFTserver/colab-convert
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Convert .py files runnable in VSCode/Python or Atom/Hydrogen to jupyter/colab .ipynb notebooks and vice versa"
  doc_url: https://github.com/MSFTserver/colab-convert
  dev_url: https://github.com/MSFTserver/colab-convert

extra:
  recipe-maintainers:
    - MSFTserver
