{% set name = "colab-convert" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3009a84a600c51bc56baf3d391e0992d8b3b0d11dfe90bbde0665c737699816c

build:
  noarch: python
  number: 0
  entry_points:
    - colab-convert = colab_convert.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - json5

test:
  imports:
    - colab_convert
    - json5

about:
  home: https://github.com/MSFTserver/colab-convert
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Convert .py files runnable in VSCode/Python or Atom/Hydrogen to jupyter/colab .ipynb notebooks and vice versa"
  doc_url: https://github.com/MSFTserver/colab-convert
  dev_url: https://github.com/MSFTserver/colab-convert

extra:
  recipe-maintainers:
    - MSFTserver
